### ISSUE TITLE
[TODO] Build system improvements

### ISSUE THREAD

**Issue by zach2good** [topaz-next/topaz#2644]
- [x] I have searched existing issues (https://github.com/topaz-next/topaz/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] This issue occurs on `release` branch (if other branch, please specify)

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
It's been maybe 6 months since I did the grand CMake refactoring, and I haven't really looked at the build since. There are some bits left over that I just couldn't be bothered to handle at the time.

**TODO:**
- Audit Windows flags; https://devblogs.microsoft.com/cppblog/recommendations-to-speed-c-builds-in-visual-studio/
- Audit clang & GCC flags; https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
- Indroduce additional build flavours (`-Ofast` and other destructive settings etc.)
- Check that the OSX build still.. exists...
- De-globalize the remaining FindLib.cmake modules
- Have the option to build all deps from source, and have a separate repo with all our deps
- Move detour's source OUT
- Build time benchmarking
- (Re-)introduce ccache and other caching mechanisms
- PCH some things

Things to consider: `fast-math` will destroy everything
